name: Deploy Prod
run-name: ${{ github.actor }} is deploying to production 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'
        
    - name: Build
      run: |
        go build -v -o pocketbase

    - name: Stop service
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.GIT_ACTIONS_USER }}
        key: ${{ secrets.GIT_ACTIONS_PRIVETE_KEY }}
        script: |
          # Ensure the service is stopped
          sudo systemctl stop pocketbase.service
        
    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.GIT_ACTIONS_USER }}
        key: ${{ secrets.GIT_ACTIONS_PRIVETE_KEY }}
        source: "pocketbase"
        target: "/home/git_actions/pb"
        overwrite: true
        
    - name: Restart application
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.GIT_ACTIONS_USER }}
        key: ${{ secrets.GIT_ACTIONS_PRIVETE_KEY }}
        script: |
          chmod +x /home/git_actions/pb/pocketbase
          sudo systemctl restart pocketbase.service
          sudo systemctl status pocketbase.service